# Generated by Django 5.1.3 on 2024-11-16 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monografia',
            fields=[
                ('idMonografia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('fechaDeDefensa', models.DateField()),
                ('notaDeLaDefensa', models.FloatField()),
                ('tiempoOtorgado', models.IntegerField()),
                ('tiempoDefensa', models.IntegerField()),
                ('tiempoDePreguntas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfesorMonografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.TextField(choices=[('Tutor', 'Tutor'), ('Jurado', 'Jurado')])),
                ('idMonografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.monografia')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Carnet', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.TextField()),
                ('Apellidos', models.TextField()),
                ('Direccion', models.TextField()),
                ('Telefono', models.TextField()),
                ('AñoDenacimiento', models.DateField()),
                ('Idmonografia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.monografia')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('idProfesor', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField()),
                ('direccion', models.TextField()),
                ('telefono', models.TextField()),
                ('añoDenacimiento', models.DateField()),
                ('monografias', models.ManyToManyField(through='api.ProfesorMonografia', to='api.monografia')),
            ],
        ),
        migrations.AddField(
            model_name='profesormonografia',
            name='idProfesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teachers'),
        ),
    ]
